language: java
jdk:
- openjdk8


addons:
    sonarcloud:
        organization: michelablack
        token: de332ab84e1ccddb3785663c646549b23ff1b8e2
        
script:
- ant build
- sonar-scanner